### ISSUE TITLE
no longer in discord

### ISSUE THREAD

**Issue by ChaseBacon** [TayMcKenzieNZ/TayMcKenzieNZ#1]
i have been in your discord for a good while  and use your emotes in my server, i have tried rejoining but it keeps saying i can't join back into discord    help  username JGreen04#5374

**Comment by TayMcKenzieNZ** [comment]
DpEmotes is protected by Warden Bot. If a user has attempted to join the server but has been banned or kicked upon joining, they will need to take this up with the Warden bot's discord server and reconsider the websites, forums and discord servers they are engaging in. It does not matter if you joined a leaking server yesterday or six months ago, the bot scans through a massive growing database and if your unique discord ID is detected, the bot springs into action.

You have unfortunately been reported as a leaker.

https://discord.gg/jeFeDRasfs

**Comment by ChaseBacon** [comment]
> 



> You have unfortunately been reported as a leaker.

you can delete this if you want Tay.. im currently trying to get it resolved.   guess leakers even make their discords look like legit devs too... though im not in either one
